default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mi_app_development

test:
  <<: *default
  database: mi_app_test

production:
  primary: &primary_production
    <<: *default
    database: mi_app_production
    username: mi_app
    password: <%= ENV["MI_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mi_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mi_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mi_app_production_cable
    migrations_paths: db/cable_migrate
